import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>WebDev Nevs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Welcome to Next</h1>
    </div>
  )
}
