import Head from 'next/head'
import ArticleList from '../components/ArticleList.js'

export default function Home({ articles }) {
  console.log(articles)
  return (
    <div>
      <Head>
        <title>WebDev Nevs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <h1>Welcome to next.js</h1>
        <ArticleList articles={articles} />
      </div>
      )
    }
    

// Fake rest API
export const getStaticProps = async () => {
  const res = await fetch('https://jsonplaceholder.typicode.com/posts?_limit=6')
  const articles = await res.json()

  // Return object 
  return {
    props: {
      articles
    }
  }
}
// Pass articles as prop to components

